version: '3.7'

services:

  nginx-proxy:

    image:  jwilder/nginx-proxy

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - type: "bin"
        source: ./certs
        target: /etc/nginx/certs
        read_only: true
      - type: "bind"
        source: /var/run/docker.sock
        target: /tmp/docker.sock
        read_only: true
      - type: "volume"
        source: "etc_nginx_vhost.d"
        target: /etc/nginx/vhost.d"
      - type: "volume"
        source: "usr_share_nginx_html"
        target: /usr/share/nginx/html

    labels:
     - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy


  letsencrypt-companion:
    
    image: jrcs/letsencrypt-nginx-proxy-companion

    volumes:
      - type: "bind"
        source: ./certs
        target: /etc/nginx/certs
      - type: "bind"
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: "volume"
        source: "etc_nginx_vhost.d"
        target: /etc/nginx/vhost.d
      - type: "volume"
        source: "usr_share_nginx_html"
        target: "/usr/share/nginx/html"

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

volumes:
  etc_nginx_vhost.d:
  usr_share_nginx_html: