version: '3'

services:
  ghost:
    image: ghost:alpine
    container_name: ghost-blog
    volumes:
      - $GHOSTCONTENT:/var/lib/ghost/content
    expose:
      - "2368"
    environment:
      - url=https://$DOMAIN
      - VIRTUAL_HOST=$DOMAIN
      - LETSENCRYPT_HOST=$DOMAIN
      - LETSENCRYPT_EMAIL=admin@antonherzog.com
      - mail__transport=SMTP
      - mail__options__service=$SMTPSERVICE
      - mail__options__auth__user=$SMTPUSER
      - mail__options__auth__pass=$SMTPPASS
    networks:
      - nginx-proxy
    restart: always

networks:
  nginx-proxy:
    external: true