version: '3'

services:
  ghost:
    image: ghost:alpine
    expose:
      - "2368"
    environment:
      - url=https://test.sqeezy.tech
      - VIRTUAL_HOST=test.sqeezy.tech
      - LETSENCRYPT_HOST=test.sqeezy.tech
      - LETSENCRYPT_EMAIL=admin@antonherzog.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true